### PR TITLE
Rebased on upstream changes

### PR DESCRIPTION
**Pull request by mappum**
I needed some of the recent changes in the upstream repo (they added a `followSymlinks` option, which will allow to add symlinks themselves rather than adding their destination files). Some of the tests are failing, but they failed before the rebase too.

### CODE REVIEW

**Comment by jbenet** [comment]
@mappum they've since added an option to avoid BOM stripping. maybe we should PR up the brfs + find good ways to do the browser fixes?

since it's a rebase github wont let me merge. you can collab, so you'll have to force-push to master (:open_mouth:) or something.

**Comment by mappum** [comment]
> they've since added an option to avoid BOM stripping.

:+1: sweet!

> maybe we should PR up the brfs + find good ways to do the browser fixes?

Maybe we should just change it to use `fs` in browserify, and `graceful-fs` in node?

**Comment by jbenet** [comment]
Yeah probably

—

**Comment by jbenet** [comment]
(Also need to deal with the source maps thing, don't recall why it was a problem)

—

**Comment by mappum** [comment]
I don't understand the point of having the `brfs` transform for this module. Did we actually want a full browser-compatible `fs` replacement such as [browserify-fs](https://github.com/mafintosh/browserify-fs)?

**Comment by jbenet** [comment]
@diasdavid made it work this way? Not sure 

—

**Comment by daviddias** [comment]
> Maybe we should just change it to use fs in browserify, and graceful-fs in node?

What is fs in browserify for you @mappum? Not sure if I get the question

**Comment by mappum** [comment]
> What is fs in browserify for you @mappum? Not sure if I get the question

I was referring to how 9122331 switched from `graceful-fs` to `fs`, I don't understand why it was changed though.

**Comment by daviddias** [comment]
If my memory lookup is not failing me, the conclusion is that graceful-fs didn't have a matching implementation for the browser, so it would break. But since fs can be browserified with brfs, which inlines any readFileSyncs and also removes fs presence, the browserified version wouldn't throw when going into that land.

**Comment by mappum** [comment]
Closing in favor of #2

**Pull request closed without merging**
